### ISSUE TITLE
Unimplemented initRequest function in SteeredWheelBaseController class

### ISSUE THREAD

**Issue by SaraTohidi** [a2s-institute/youbot_simulation#7]
Hello everyone,

I get the youbot_simulation and youbot_description packages while I have Ubuntu 16.04 and ROS_Kinetic branch with gazebo7.

But the problem is when I make the packages an error shows up from the youbot_gazebo_control which says one virtual function doesn't implement. and I find out it was from this function:

```
virtual bool initRequest(hardware_interface::RobotHW *robot_hw,
                             ros::NodeHandle &root_nh,
                             ros::NodeHandle &controller_nh,
                             ClaimedResources &claimed_resources);
```

I would really appreciate any help to fix this.

**Comment by sthoduka** [comment]
This is a result of [this](https://github.com/ros-controls/ros_control/commit/3694abf51d900235254f093b1fb59333474b062a) commit in ros_control. 
The issue is described [here](https://github.com/ros-controls/ros_control/issues/75)

the initRequest function needs to be updated to match the current API.

**Comment by SynapseProgramming** [comment]
Hi everyone,
the main reason why the initRequest function does not implement is because ros control has changed 
the type of the claimed_resources argument from std::set<std::string> to ClaimedResourcesType. Hence, changes have to be made to functions which make use of this argument. 
[steered_wheel_base_controller.txt](https://github.com/mas-group/youbot_simulation/files/816799/steered_wheel_base_controller.txt)

The attached steered_wheel_base_controller file is updated to work on (ROS Kinetic , Ubuntu 16.04 LTS) 
In order for it to work, please change the file extension from steered_wheel_base_controller.txt to steered_wheel_base_controller.cpp, 

And place it in the youbot_gazebo_control/src directory. 

Thanks!!!

**Comment by SaraTohidi** [comment]
Thank you so much!
I've replaced the file and that works fine now.

**Comment by sthoduka** [comment]
FYI, the changes from @SynapseProgramming have been merged into [kinetic-devel](https://github.com/mas-group/youbot_simulation/tree/kinetic-devel)
Thanks!
